# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rapi.autogen.openapi_server.models.base_model_ import Model
from rapi.autogen.openapi_server import util


class Cuisine(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None):  # noqa: E501
        """Cuisine - a model defined in OpenAPI

        :param id: The id of this Cuisine.  # noqa: E501
        :type id: int
        :param name: The name of this Cuisine.  # noqa: E501
        :type name: str
        """
        self.openapi_types = {
            'id': int,
            'name': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name'
        }

        self._id = id
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'Cuisine':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Cuisine of this Cuisine.  # noqa: E501
        :rtype: Cuisine
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Cuisine.


        :return: The id of this Cuisine.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Cuisine.


        :param id: The id of this Cuisine.
        :type id: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Cuisine.


        :return: The name of this Cuisine.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Cuisine.


        :param name: The name of this Cuisine.
        :type name: str
        """

        self._name = name
